### ISSUE TITLE
Builder feature proposal: template specific colors

### ISSUE THREAD

**Issue by mienaikage** [chriskempson/base16#179]
An example scenario: You may have a color scheme that looks great on your shell, but the syntax highlighting isn't set up quite the way you like it. Conversely, adjusting the syntax highlighting to your preference results in mixing up the shell colors.

I propose the ability to add a key for a template, defining colors specific to that template. Any colors not defined for that template can fall back to the standard definitions.

For example:
```yaml
scheme: Example
author: Exemplar
base00: '282a36' # Background
base01: '343746' # Lighter Background
base02: '44475a' # Selection
base03: '6272a4' # Comments
base04: '999999' # Dark Foreground (status bars)
base05: 'f8f8f2' # Foreground
base06: 'f8f8f2' # Light Foreground
base07: 'f8f8f2' # Light Background
base08: &red    'ff5555'
base09: &purple 'bd93f9'
base0A: &yellow 'f1fa8c'
base0B: &green  '50fa7b'
base0C: &cyan   '8be9fd'
base0D: &blue   '66d9ef'
base0E: &pink   'ff79c6'
base0F: &orange 'ffb86c'

templates:
  vim:
    base08: *cyan
    base0A: *red
    base0C: *yellow
```

All would build as normal, aside from vim, which would build with the colors specified in its key, and use the original colors for ones not defined in said key.
