### ISSUE TITLE
Can the prefix be made optional or configurable?

### ISSUE THREAD

**Issue by joshgoebel** [chriskempson/base16#260]
> The theme filename should look like base16-[slug][extension]

I'd like a way to remove the `base16-`... I'm just vendoring all the files into a `base16` folder so it's entirely redundant...

Consider:

```
default:
  namePrefix: ""
  extension: .yml
  output: colors
```

Thoughts?
